# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: The Story of Open Opportunities
subtitle:

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: ''

# Author/Organization info to be displayed in the templates
author:
  name: Name
  url: http://localhost:4000

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Welcome
  url: ./
  internal: true
- text: Origins at GSA
  url: getting-started/
  internal: true

#- text: DOCter Repo
#  url: https://github.com/cfpb/DOCter
#  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: This Website
  description: Open Opportunities story
  url: https://github.com/openopps/openopps.github.io
- name: OpenOpps Platform
  description: Open source software
  url: https://github.com/openopps/openopps-platform

# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
